### ISSUE TITLE
Image uploads aren't rendering

### ISSUE THREAD

**Issue by ggpext** [jaescalo/Akamai-Netstorage-API-Postman#1]
Hi. the example images you've uploaded aren't accessible any more.

**Comment by jaescalo** [comment]
Hey... I see them just fine and tried with different browsers just in case. 
The images are under the /images folder and the README file is referencing them properly. Can you double check maybe with a different browser?

**Comment by ggpext** [comment]
hi. yes i looked on a different browser and whilst logged in/logged out. still can't see them. 
It's referencing them from here 
https://raw.githubusercontent.com/jaescalo/Akamai-Netstorage-API-Postman/main/images/ns_env_variables.jpg

**Comment by jaescalo** [comment]
Weird, I'm using relative references. Anyway I just chanced to absolute references which should work as well.

**Comment by ggpext** [comment]
Sadly they still aren't working for me. i have tried another device with the same result. can you try with another device like a phone?

**Comment by ggpext** [comment]
sorry, turns it was corporate internet policy blocking them.

**Comment by jaescalo** [comment]
Makes sense, thanks for letting me know.

**Comment by jaescalo** [comment]
Closed
