### ISSUE TITLE
Suggestion: Add Postman setup instruction for selecting the created environment

### ISSUE THREAD

**Issue by aldrichdev** [jaescalo/Akamai-Netstorage-API-Postman#2]
Users that are not well-versed with Postman may neglect to select the Akamai environment that we create in Step 1 of the setup instructions in the readme - resulting in an error with the Pre-request script, `Cannot read property 'sigBytes' of undefined`. I suggest you add a step under Step 3 of the Request section that specifically mentions selecting the created environment in the dropdown.

**Comment by jaescalo** [comment]
Great stuff! Step documented.
